name: Build OS

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Cache Buildroot download folder (dl/)
        uses: actions/cache@v4
        with:
          path: buildroot/dl
          key: buildroot-dl-${{ hashFiles('buildroot/**') }}
          restore-keys: |
            buildroot-dl-

      - name: Cache ccache
        uses: actions/cache@v4
        with:
          path: ~/.ccache
          key: ccache-${{ hashFiles('buildroot/**') }}
          restore-keys: |
            ccache-

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential bc bison flex gettext \
            libncurses5-dev libssl-dev python3 unzip \
            wget rsync file cpio python3-pyelftools \
            git make gcc g++ tar xz-utils \
            ccache

      - name: Enable ccache
        run: |
          echo 'export BR2_CCACHE=y' >> buildroot/.config
          echo 'export CCACHE_DIR=${HOME}/.ccache' >> $GITHUB_ENV
          echo 'export CCACHE_MAXSIZE=500M' >> $GITHUB_ENV
          echo 'export PATH="/usr/lib/ccache:$PATH"' >> $GITHUB_ENV

      - name: Set Buildroot config
        working-directory: buildroot
        run: make raspberrypi4_64_defconfig

      - name: Enable external toolchain (Linaro ARM64)
        working-directory: buildroot
        run: |
          make menuconfig <<EOF
          BR2_TOOLCHAIN_EXTERNAL=y
          BR2_TOOLCHAIN_EXTERNAL_LINARO_AARCH64=y
          EOF

      - name: Build Buildroot (parallel)
        working-directory: buildroot
        env:
          CCACHE_DIR: ~/.ccache
          BR2_CCACHE: y
        run: |
          make BR2_JLEVEL=$(nproc)

      - name: Upload output image
        uses: actions/upload-artifact@v4
        with:
          name: buildroot-rpi4_64
          path: buildroot/output/images/
