name: Build OS

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            bc \
            bison \
            flex \
            gettext \
            libncurses5-dev \
            libssl-dev \
            python3 \
            unzip \
            wget \
            rsync \
            file \
            cpio \
            python3-pyelftools \
            git \
            make \
            gcc \
            g++ \
            tar \
            xz-utils

      - name: Set Buildroot config
        working-directory: buildroot
        run: make raspberrypi4_64_defconfig

      - name: Build Buildroot
        working-directory: buildroot
        run: make

      - name: Upload output image
        uses: actions/upload-artifact@v4
        with:
          name: buildroot-rpi4_64
          path: buildroot/output/images/
