name: Build OS

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Cache ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          create-symlink: true

      - name: Cache Buildroot download folder (dl/)
        uses: actions/cache@v4
        with:
          path: buildroot/dl
          key: buildroot-dl-cache-v1
          restore-keys: |
            buildroot-dl-

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential bc bison flex gettext \
            libncurses5-dev libssl-dev python3 unzip \
            wget rsync file cpio python3-pyelftools \
            git make gcc g++ tar xz-utils \
            ccache

      - name: Enable ccache
        run: |
          echo 'export BR2_CCACHE_DIR=${HOME}/.ccache' >> $GITHUB_ENV

      - name: Build Buildroot (parallel)
        working-directory: buildroot
        env:
          CCACHE_DIR: ~/.ccache
        run: |
          make BR2_EXTERNAL=../buildroot-external rpi4_64_defconfig
          make BR2_JLEVEL=$(nproc)

      - name: Upload output image
        uses: actions/upload-artifact@v4
        with:
          name: buildroot-rpi4_64
          path: buildroot/output/images/
